name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Basic build job with SonarQube analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional: install dependencies and run tests before scanning
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '17'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test


          # Set up NodeJS 
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install NodeJS dependencies
      - name: Install NodeJS dependencies
        run: npm install

      # SonarQube Analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

 # Docker Image Build
      - name: Build Docker Image
        run: docker build -t actions-app:${{ github.sha}} .

  # Trivy Scan
      - name: Trivy Scan
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image actions-app:${{ github.sha}}


  # Log in to Amazon ECR
     - name: Log in to Amazon ECR
       run:  # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}
