name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Debug secrets (safe check, doesn’t print values)
      - name: Debug secrets
        run: |
          echo "Checking if secrets are set..."
          [ -z "${{ secrets.SONAR_TOKEN }}" ] && echo "❌ SONAR_TOKEN is NOT set" || echo "✅ SONAR_TOKEN is set"
          [ -z "${{ secrets.ECR_REPOSITORY_URI }}" ] && echo "❌ ECR_REPOSITORY_URI is NOT set" || echo "✅ ECR_REPOSITORY_URI is set"
          [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] && echo "❌ DOCKERHUB_USERNAME is NOT set" || echo "✅ DOCKERHUB_USERNAME is set"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Run tests
        run: npm test

      # SonarQube / SonarCloud Analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t actions-app:${{ github.sha }} .

      # Push image to Amazon ECR
      - name: Push image to Amazon ECR
        run: |
          docker tag actions-app:${{ github.sha }} ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker tag actions-app:${{ github.sha }} ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}

          
         
